pipeline {
    agent any
    options {
        timeout(time: 20, unit: 'MINUTES')
    }
    environment {
        TF_IN_AUTOMATION = 'true'  // Run Terraform in automation mode
    }
    stages {
        stage('Checkout repo') {
            steps {
                checkout scmGit(
                branches: [[name: 'master']],
                userRemoteConfigs: [[url: 'https://github.com/Hardik-Ahi/testProject-2.git']]
                )
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t html:latest .'
                sh 'docker tag html:latest ahihardik11/html'
                sh 'docker push ahihardik11/html:latest'
            }
        }
        stage('Terraform infrastructure') {
            steps {
                dir('terraform') {
                    script {
                        sh 'terraform init'
                        int checkCode = sh(
                            script: 'terraform plan -detailed-exitcode',
                            returnStatus: true
                        )
                        
                        if (checkCode == 0) {
                            echo "Infrastructure exists. Replacing EC2 instance"
                            sh 'terraform plan -replace="aws_instance.demo" -input=false -out=tfplan'
                        } else if (checkCode == 2) {
                            echo "Infrastructure does not exist or is incomplete. Creating everything..."
                            sh 'terraform plan -input=false -out=tfplan'
                        } else {
                            error "Terraform plan failed."
                        }

                        sh 'terraform apply -input=false tfplan'
                    }
                }
            }
        }
    }
}
